GAME_SELECTED_SESSION_ID = "game_selected_session"
ERROR_MESSAGE_ID = "msg_error"
COUNTER_SESSION_ID = "counter_session"
COUNTER_GLOBAL_ID = "counter_global"
SUCCESS_MESSAGE_ID = "msg_success"
INFO_MESSAGE_ID = "msg_info"